### PR TITLE
Update werhlemodwm.xmq

### PR DESCRIPTION
**Pull request by kzajac83**
Adding missing fields form werhlemodwm.xmq driver.

### CODE REVIEW

**Review by kzajac83 — COMMENTED** [review]
Revied

**Comment by kzajac83** [comment]
Thank for trick, changed and tested, working good from my site

**Comment by weetmuts** [comment]
Ah, do you have a complete test telegram?  The one in the test case is truncated...

**Comment by weetmuts** [comment]
Ah, found it in a previous commit. All good. :-)

**Pull request merged**
