### PR TITLE
Add Eltako DSZ15DM driver

### PR DESCRIPTION
**Pull request by probutus**
Eltako DSZ15DM meter driver for wired mbus added
Datasheet is here
[M-Bus_Stromzaehler_Technische_Daten_Einlernhilfe.pdf](https://github.com/wmbusmeters/wmbusmeters/files/15447128/M-Bus_Stromzaehler_Technische_Daten_Einlernhilfe.pdf)

### CODE REVIEW

**Comment by weetmuts** [comment]
You create eltako.xmq and make sure the name is eltako then you do:

wmbusmeters --analyze=eltako.xmq <telegramhex>

**Comment by weetmuts** [comment]
At least one test telegram should also be added. :-)

**Comment by probutus** [comment]
Hi Fredrik, 
thanks a lot for the timely response. I created an xmq file to the best of my knowledge but it fails to pick up most of the values. Unfortunately the examples do not show how I can add parameters like StorageNr, TariffNr, SubunitNr and VIFcombinable. I attached my most recent attempt below. I would be very grateful if you could have a look and give some guidance on what I did wrong?

I have an example telegram:
wmbusmeters --analyze=eltako.xmq  
root@andromeda:/home/pi/wmbusmeters# ./build/wmbusmeters --analyze=eltako.xmq 689292680800723612452394150102cd0000008c1004688902008c1104688902008c2004000000008c21040000000002fdc9ff01ee0002fddBff01100002acff0120008240acff010a0002fdc9ff02ef0002fddBff02110002acff0224008240acff02070002fdc9ff03ee0002fddBff030e0002acff031c008240acff03060002ff68010002acff0062008240acff00190001ff1300f416

xmq file is here:
[eltako.xmq.gz](https://github.com/wmbusmeters/wmbusmeters/files/15459028/eltako.xmq.gz)

**Comment by weetmuts** [comment]
I pushed a fix, it was not reading the tariff_nr and subunit_nrs yet in the driver loading code.

./build/wmbusmeters --analyze=eltako.xmq 689292680800723612452394150102cd0000008c1004688902008c1104688902008c2004000000008c21040000000002fdc9ff01ee0002fddBff01100002acff0120008240acff010a0002fdc9ff02ef0002fddBff02110002acff0224008240acff02070002fdc9ff03ee0002fddBff030e0002acff031c008240acff03060002ff68010002acff0062008240acff00190001ff1300f416
 
```
[eltako.xmq.gz](https://github.com/wmbusmeters/wmbusmeters/files/15462215/eltako.xmq.gz)

**Comment by weetmuts** [comment]
Check the attached xmq driver file. It seems to be decoding all the fields. 

```
Auto driver  : eltako
Best driver  : eltako 47/47
Using driver : eltako 00/00
000   : 68 start
001   : 92 length (146 bytes)
002   : 92 length again (146 bytes)
003   : 68 start
004   : 08 dll-c (RSP_UD2)
005   : 00 dll-a primary (0)
006   : 72 tpl-ci (long header)
007   : 36124523 tpl-id (23451236)
011   : 9415 tpl-mfct (ELT)
013   : 01 tpl-version
014   : 02 tpl-type (Electricity meter)
015   : cd tpl-acc-field
016   : 00 tpl-sts-field (OK)
017   : 0000 tpl-cfg 0000 ( )
019   : 8C dif (8 digit BCD Instantaneous value)
020   : 10 dife (subunit=0 tariff=1 storagenr=0)
021   : 04 vif (Energy 10¹ Wh)
022 C!: 68890200 ("total_tariff_1_kwh":289.68)
026   : 8C dif (8 digit BCD Instantaneous value)
027   : 11 dife (subunit=0 tariff=1 storagenr=2)
028   : 04 vif (Energy 10¹ Wh)
029 C!: 68890200 ("total_reactive_tariff_1_kwh":289.68)
033   : 8C dif (8 digit BCD Instantaneous value)
034   : 20 dife (subunit=0 tariff=2 storagenr=0)
035   : 04 vif (Energy 10¹ Wh)
036 C!: 00000000 ("total_tariff_2_kwh":0)
040   : 8C dif (8 digit BCD Instantaneous value)
041   : 21 dife (subunit=0 tariff=2 storagenr=2)
042   : 04 vif (Energy 10¹ Wh)
043 C!: 00000000 ("total_reactive_tariff_2_kwh":0)
047   : 02 dif (16 Bit Integer/Binary Instantaneous value)
048   : FD vif (Second extension FD of VIF-codes)
049   : C9 vife (10^0 Volts)
050   : FF combinable vif (MfctSpecific)
051   : 01 combinable extension vife (Mfct01)
052 C!: EE00 ("voltage_l1_n_v":238)
054   : 02 dif (16 Bit Integer/Binary Instantaneous value)
055   : FD vif (Second extension FD of VIF-codes)
056   : DB vife (10^-1 Ampere)
057   : FF combinable vif (MfctSpecific)
058   : 01 combinable extension vife (Mfct01)
059 C!: 1000 ("current_l1_a":1.6)
061   : 02 dif (16 Bit Integer/Binary Instantaneous value)
062   : AC vif (Power 10¹ W)
063   : FF combinable vif (MfctSpecific)
064   : 01 combinable extension vife (Mfct01)
065 C!: 2000 ("power_l1_kw":0.32)
067   : 82 dif (16 Bit Integer/Binary Instantaneous value)
068   : 40 dife (subunit=1 tariff=0 storagenr=0)
069   : AC vif (Power 10¹ W)
070   : FF combinable vif (MfctSpecific)
071   : 01 combinable extension vife (Mfct01)
072 C!: 0A00 ("reactive_power_l1_kw":0.1)
074   : 02 dif (16 Bit Integer/Binary Instantaneous value)
075   : FD vif (Second extension FD of VIF-codes)
076   : C9 vife (10^0 Volts)
077   : FF combinable vif (MfctSpecific)
078   : 02 combinable extension vife (Mfct02)
079 C!: EF00 ("voltage_l2_n_v":239)
081   : 02 dif (16 Bit Integer/Binary Instantaneous value)
082   : FD vif (Second extension FD of VIF-codes)
083   : DB vife (10^-1 Ampere)
084   : FF combinable vif (MfctSpecific)
085   : 02 combinable extension vife (Mfct02)
086 C!: 1100 ("current_l2_a":1.7)
088   : 02 dif (16 Bit Integer/Binary Instantaneous value)
089   : AC vif (Power 10¹ W)
090   : FF combinable vif (MfctSpecific)
091   : 02 combinable extension vife (Mfct02)
092 C!: 2400 ("power_l2_kw":0.36)
094   : 82 dif (16 Bit Integer/Binary Instantaneous value)
095   : 40 dife (subunit=1 tariff=0 storagenr=0)
096   : AC vif (Power 10¹ W)
097   : FF combinable vif (MfctSpecific)
098   : 02 combinable extension vife (Mfct02)
099 C!: 0700 ("reactive_power_l2_kw":0.07)
101   : 02 dif (16 Bit Integer/Binary Instantaneous value)
102   : FD vif (Second extension FD of VIF-codes)
103   : C9 vife (10^0 Volts)
104   : FF combinable vif (MfctSpecific)
105   : 03 combinable extension vife (Mfct03)
106 C!: EE00 ("voltage_l3_n_v":238)
108   : 02 dif (16 Bit Integer/Binary Instantaneous value)
109   : FD vif (Second extension FD of VIF-codes)
110   : DB vife (10^-1 Ampere)
111   : FF combinable vif (MfctSpecific)
112   : 03 combinable extension vife (Mfct03)
113 C!: 0E00 ("current_l3_a":1.4)
115   : 02 dif (16 Bit Integer/Binary Instantaneous value)
116   : AC vif (Power 10¹ W)
117   : FF combinable vif (MfctSpecific)
118   : 03 combinable extension vife (Mfct03)
119 C!: 1C00 ("power_l3_kw":0.28)
121   : 82 dif (16 Bit Integer/Binary Instantaneous value)
122   : 40 dife (subunit=1 tariff=0 storagenr=0)
123   : AC vif (Power 10¹ W)
124   : FF combinable vif (MfctSpecific)
125   : 03 combinable extension vife (Mfct03)
126 C!: 0600 ("reactive_power_l3_kw":0.06)
128   : 02 dif (16 Bit Integer/Binary Instantaneous value)
129   : FF vif (Manufacturer specific)
130   : 68 vife (?)
131 C!: 0100 ("ct_numerator_counter":1)
133   : 02 dif (16 Bit Integer/Binary Instantaneous value)
134   : AC vif (Power 10¹ W)
135   : FF combinable vif (MfctSpecific)
136   : 00 combinable extension vife (Mfct00)
137 C!: 6200 ("active_power_overall_kw":0.98)
139   : 82 dif (16 Bit Integer/Binary Instantaneous value)
140   : 40 dife (subunit=1 tariff=0 storagenr=0)
141   : AC vif (Power 10¹ W)
142   : FF combinable vif (MfctSpecific)
143   : 00 combinable extension vife (Mfct00)
144 C!: 1900 ("reactive_power_overall_kw":0.25)
146   : 01 dif (8 Bit Integer/Binary Instantaneous value)
147   : FF vif (Manufacturer specific)
148   : 13 vife (?)
149 C!: 00 ("active_tariff_counter":0)
150   : F4 crc
151   : 16 end

{
    "media":"electricity",
    "meter":"eltako",
    "name":"",
    "id":"23451236",
    "active_power_overall_kw":0.98,
    "active_tariff_counter":0,
    "ct_numerator_counter":1,
    "current_l1_a":1.6,
    "current_l2_a":1.7,
    "current_l3_a":1.4,
    "power_l1_kw":0.32,
    "power_l2_kw":0.36,
    "power_l3_kw":0.28,
    "reactive_power_l1_kw":0.1,
    "reactive_power_l2_kw":0.07,
    "reactive_power_l3_kw":0.06,
    "reactive_power_overall_kw":0.25,
    "total_reactive_tariff_1_kwh":289.68,
    "total_reactive_tariff_2_kwh":0,
    "total_tariff_1_kwh":289.68,
    "total_tariff_2_kwh":0,
    "voltage_l1_n_v":238,
    "voltage_l2_n_v":239,
    "voltage_l3_n_v":238,
    "timestamp":"2024-05-27T22:43:20Z"
}
```

**Comment by weetmuts** [comment]
```
driver {
    name           = eltako
    default_fields = name,id,total_energy_consumption_kwh,timestamp
    meter_type     = ElectricityMeter
    detect {
        mvt = ELT,01,02
    }
    field {
        name     = status
        quantity = Text
        info     = status_and_error_flags
        match {
            measurement_type = Instantaneous
            vif_range        = ErrorFlags
        }
        lookup {
            name            = ERROR_FLAGS
            map_type        = BitToString
            mask_bits       = 0xff
            default_message = OK
            map {
                name  = BUSY
                info  = 'System is busy'
                value = 0x01
                test  = Set
            }
            map {
                name  = GENERIC_APP_ERROR
                info  = 'Generic application error'
                value = 0x02
                test  = Set
            }
            map {
                name  = CURRENT_LOW
                info  = 'Current too low'
                value = 0x04
                test  = Set
            }
            map {
                name  = PERMANENT_ERROR
                info  = 'permanent error'
                value = 0x08
                test  = Set
            }
            map {
                name  = TEMPORARY_ERROR
                info  = 'temporary error'
                value = 0x10
                test  = Set
            }
        }
    }
    field {
        name     = 'total_tariff_{tariff_counter}'
        quantity = Energy
        info     = 'Total cumulative active energy per tariff.'
        match {
            measurement_type = Instantaneous
            vif_scaling      = Auto
            vif_range        = AnyEnergyVIF
            tariff_nr        = 1,10
        }
    }
    field {
        name     = 'total_reactive_tariff_{tariff_counter}'
        quantity = Energy
        info     = 'Total cumulative reactive energy per tariff.'
        match {
            measurement_type = Instantaneous
            vif_scaling      = Auto
            vif_range        = AnyEnergyVIF
            storage_nr       = 2
            tariff_nr        = 1,10
        }
    }
    field {
        name     = voltage_l1_n
        quantity = Voltage
        info     = 'Instantaneous voltage between L1 and neutral.'
        match {
            measurement_type = Instantaneous
            vif_scaling      = Auto
            vif_range        = Voltage
            add_combinable   = Mfct01
        }
    }
    field {
        name     = current_l1
        quantity = Amperage
        info     = 'Instantaneous current in the L1 phase.'
        match {
            measurement_type = Instantaneous
            vif_scaling      = Auto
            vif_range        = Amperage
            add_combinable   = Mfct01
        }
    }
    field {
        name     = power_l1
        quantity = Power
        info     = 'active Power in L1 phase'
        match {
            measurement_type = Instantaneous
            vif_scaling      = Auto
            vif_range        = AnyPowerVIF
            add_combinable   = Mfct01
        }
    }
    field {
        name     = reactive_power_l1
        quantity = Power
        info     = 'reactive Power in L1 phase'
        match {
            measurement_type = Instantaneous
            vif_scaling      = Auto
            vif_range        = AnyPowerVIF
            subunit_nr       = 1
            add_combinable   = Mfct01
        }
    }
    field {
        name     = voltage_l2_n
        quantity = Voltage
        info     = 'Instantaneous voltage between L2 and neutral.'
        match {
            measurement_type = Instantaneous
            vif_scaling      = Auto
            vif_range        = Voltage
            add_combinable   = Mfct02
        }
    }
    field {
        name     = current_l2
        quantity = Amperage
        info     = 'Instantaneous current in the L2 phase.'
        match {
            measurement_type = Instantaneous
            vif_scaling      = Auto
            vif_range        = Amperage
            add_combinable   = Mfct02
        }
    }
    field {
        name     = power_l2
        quantity = Power
        info     = 'active Power in L2 phase'
        match {
            measurement_type = Instantaneous
            vif_scaling      = Auto
            vif_range        = AnyPowerVIF
            add_combinable   = Mfct02
        }
    }
    field {
        name     = reactive_power_l2
        quantity = Power
        info     = 'reactive Power in L2 phase'
        match {
            measurement_type = Instantaneous
            vif_scaling      = Auto
            vif_range        = AnyPowerVIF
            subunit_nr       = 1
            add_combinable   = Mfct02
        }
    }
    field {
        name     = voltage_l3_n
        quantity = Voltage
        info     = 'Instantaneous voltage between L3 and neutral.'
        match {
            measurement_type = Instantaneous
            vif_scaling      = Auto
            vif_range        = Voltage
            add_combinable   = Mfct03
        }
    }
    field {
        name     = current_l3
        quantity = Amperage
        info     = 'Instantaneous current in the L3 phase.'
        match {
            measurement_type = Instantaneous
            vif_scaling      = Auto
            vif_range        = Amperage
            add_combinable   = Mfct03
        }
    }
    field {
        name     = power_l3
        quantity = Power
        info     = 'active Power in L3 phase'
        match {
            measurement_type = Instantaneous
            vif_scaling      = Auto
            vif_range        = AnyPowerVIF
            add_combinable   = Mfct03
        }
    }
    field {
        name     = reactive_power_l3
        quantity = Power
        info     = 'reactive Power in L3 phase'
        match {
            measurement_type = Instantaneous
            vif_scaling      = Auto
            vif_range        = AnyPowerVIF
            subunit_nr       = 1
            add_combinable   = Mfct03
        }
    }
    field {
        name = ct_numerator
        info = 'Current transformer ratio (numerator)'
        quantity = Dimensionless
        vif_scaling = None
        match {
            difvifkey = 02FF68
        }
    }
    field {
        name     = active_power_overall
        quantity = Power
        info     = 'active Power overall'
        match {
            measurement_type = Instantaneous
            vif_scaling      = Auto
            vif_range        = AnyPowerVIF
            add_combinable   = Mfct00
        }
    }
    field {
        name     = reactive_power_overall
        quantity = Power
        info     = 'reactive Power overall'
        match {
            measurement_type = Instantaneous
            vif_scaling      = Auto
            vif_range        = AnyPowerVIF
            subunit_nr       = 1
            add_combinable   = Mfct00
        }
    }

    field {
        name = active_tariff
        info = 'active tariff'
        quantity = Dimensionless
        vif_scaling = None
        match {
            difvifkey = 01FF13
        }
    }

    test {
        args = 'Eltako eltako 23451236 NOKEY'
        telegram = 689292680800723612452394150102cd0000008c1004688902008c1104688902008c2004000000008c21040000000002fdc9ff01ee0002fddBff01100002acff0120008240acff010a0002fdc9ff02ef0002fddBff02110002acff0224008240acff02070002fdc9ff03ee0002fddBff030e0002acff031c008240acff03060002ff68010002acff0062008240acff00190001ff1300f416
        json = ''
        fields = ''
    }

}
```

**Comment by weetmuts** [comment]
If you want, then you can download the xmq tool to pretty print the driver from here: https://libxmq.org
xmq eltako.xmq
xmq eltako.xmq pa
xmq eltako.xmq br

You can also upload the driver from the same webpage to get it pretty printed online.

**Comment by probutus** [comment]
Hi Fredrik,
I tested the most recent changes. Via --analyse all elements were picked up correctly. However when I installed it, wmbusmeters crashed with a segfault. This also happens without having the new xmq in place. I attached the strace log

[strace.out.gz](https://github.com/wmbusmeters/wmbusmeters/files/15473913/strace.out.gz)

**Comment by weetmuts** [comment]
can you run with --debug ?

**Comment by weetmuts** [comment]
Check that you did "make clean" before the build.
You can also build: make DEBUG=true and install build_debug/wmbusmeters
then  you will get a stack trace.

**Comment by probutus** [comment]
Hi Fredrik,

thanks a lot for the quick response. I did a make clean beforehand but the problem persists. I did a debuglog with the regular build:

[debuglog.txt.gz](https://github.com/wmbusmeters/wmbusmeters/files/15475666/debuglog.txt.gz)

the wmbusmeters.drivers.d directory is empty

I tried to run a make DEBUG=true but this build failed in linker phase with

/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/12/libasan.so: undefined reference to `__atomic_store_8'
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/12/libasan.so: undefined reference to `__atomic_load_8'
collect2: error: ld returned 1 exit status

**Comment by probutus** [comment]
HI Fredrik,
took me a bit of time to figure out what was going on. I had to update rtlsdr along with wmbusmeters. This resolved the startup crash. What also was an issue that if you have the eltako.xmq file in /etc/wmbusmeters.drivers.d and in the source folder the system stops. Using --debug gave me the right hint that it was overridden

latest version is working nicely with my electricity meter

Should I close this pull request as I see the XMQ file is alredy created?

**Comment by weetmuts** [comment]
Great that you found it! Yes, we can close this now. Mission accomplished and congratulations to be the first person apart from me who have create a text driver.

**Comment by weetmuts** [comment]
I think I should make wmbusmeters always print if the built in driver has been overriden. (ie not hidden inside debug)

**Comment by weetmuts** [comment]
It should be possible to override the built in drivers.

**Pull request closed without merging**
