### PR TITLE
Update docker image, add rtl_reset

### PR DESCRIPTION
**Pull request by testuser7**
Use latest alpine docker image with latest rtl_433 alpine package version.
Add rtl_reset to docker image.

Continuation: https://github.com/wmbusmeters/wmbusmeters/pull/991

For now, the only solution that works in my case is this code:
```rtl433:CMD(rtl_433 -R 104 -Y squelch -F csv -f 868.95M -s 1.6m; exit_code=$?; if [ $exit_code -ge 3 ]; then echo "`date '+%F %T %Z'` Reset rtl-sdr dongle (exit code: $exit_code)" >> /wmbusmeters_data/logs/wmbusmeters.log && rtl_reset && false; fi)```

`rtlsdr` even with this [change](https://github.com/steve-m/librtlsdr/commit/142325a93c6ad70f851f43434acfdf75e12dfe03) is not working properly.

Before merge you can check docker images from this repo: https://github.com/testuser7/wmbusmeters/pkgs/container/wmbusmeters/174628366?tag=dev (arm and arm64 architectures are not tested)

### CODE REVIEW

**Comment by weetmuts** [comment]
Awesome! But can you re-add rtl_433 and add rtl_sdr? ;-) 

The underlying OS is not controlled by our docker image, it is controlled by the HA setup itself, which is/was not updated to the latest alpine.  See BIBOs comment here: https://github.com/wmbusmeters/wmbusmeters/issues/1151

So we have to build rtl_sdr to get the latest rtl_sdr for the latest dongles, and get this important bug fix: https://github.com/osmocom/rtl-sdr/commit/142325a93c6ad70f851f43434acfdf75e12dfe03

**Comment by testuser7** [comment]
For alpine v3.19 used in this case we have latest versions of rtl_433 and rtl-sdr:
```
/wmbusmeters # apk info rtl_433
WARNING: opening from cache https://dl-cdn.alpinelinux.org/alpine/v3.19/main: No such file or directory
WARNING: opening from cache https://dl-cdn.alpinelinux.org/alpine/v3.19/community: No such file or directory
rtl_433-23.11-r0 description:
Program to decode transmissions on the ISM bands

rtl_433-23.11-r0 webpage:
https://github.com/merbanan/rtl_433

rtl_433-23.11-r0 installed size:
880 KiB

/wmbusmeters # apk info rtl-sdr
WARNING: opening from cache https://dl-cdn.alpinelinux.org/alpine/v3.19/main: No such file or directory
WARNING: opening from cache https://dl-cdn.alpinelinux.org/alpine/v3.19/community: No such file or directory
rtl-sdr-2.0.1-r0 description:
Software defined radio receiver for Realtek RTL2832U (tools)

rtl-sdr-2.0.1-r0 webpage:
https://osmocom.org/projects/sdr/wiki/rtl-sdr

rtl-sdr-2.0.1-r0 installed size:
204 KiB

/wmbusmeters # apk info librtlsdr
WARNING: opening from cache https://dl-cdn.alpinelinux.org/alpine/v3.19/main: No such file or directory
WARNING: opening from cache https://dl-cdn.alpinelinux.org/alpine/v3.19/community: No such file or directory
librtlsdr-2.0.1-r0 description:
Software defined radio receiver for Realtek RTL2832U

librtlsdr-2.0.1-r0 webpage:
https://osmocom.org/projects/sdr/wiki/rtl-sdr

librtlsdr-2.0.1-r0 installed size:
80 KiB

```

**Comment by testuser7** [comment]
The workflow has been updated (metadata merge has been added).

**Comment by BIBOLV** [comment]
I`m currently [testing](https://github.com/BIBOLV/wmbusmeters/blob/master/docker/Dockerfile#L6) rtl-sdr building from source to not be tied to underlying OS differences.

**Comment by testuser7** [comment]
I added building `librtlsdr` and `rtl_433` from sources.

**Comment by BIBOLV** [comment]
Tested on arm64 - image started, but with following error:
```
(main) rtlsdr device  not currently used.
(main) opening rtlwmbus
Started auto rtlwmbus listening on t1
(shell) exec (capture output) "/usr/bin/rtl_wmbus"
(shell) arg "-h"
(shell) output: >>>/usr/bin/rtl_wmbus: unrecognized option: h
rtl_wmbus: 1.0.1-5-g6c4f95f

Usage /usr/bin/rtl_wmbus:
        -a accelerate (use an inaccurate atan version)
        -r 0 to disable run length algorithm
        -t 0 to disable time2 algorithm
        -d 2 set decimation rate to 2 (defaults to 2 if omitted)
        -v show used algorithm in the output
        -V show version
        -s receive S1 and T1/C1 datagrams simultaneously. rtl_sdr _MUST_ be set to 868.625MHz (-f 868.625M)
        -p [T,S] to disable processing T1/C1 or S1 mode.
        -f exit if incoming data stalled for 5 seconds.
        -h print this help
<<<
(serial) EVENT thread interrupted
(shell) return code 1
(shell) 1159 exited
(rtlwmbus) help /usr/bin/rtl_wmbus: unrecognized option: h
rtl_wmbus: 1.0.1-5-g6c4f95f

Usage /usr/bin/rtl_wmbus:
        -a accelerate (use an inaccurate atan version)
        -r 0 to disable run length algorithm
        -t 0 to disable time2 algorithm
        -d 2 set decimation rate to 2 (defaults to 2 if omitted)
        -v show used algorithm in the output
        -V show version
        -s receive S1 and T1/C1 datagrams simultaneously. rtl_sdr _MUST_ be set to 868.625MHz (-f 868.625M)
        -p [T,S] to disable processing T1/C1 or S1 mode.
        -f exit if incoming data stalled for 5 seconds.
        -h print this help

Warning! rtl_wbus executable lacks -f option! Without this option rtl_wmbus cannot detect when rtl-sdr stops working.
Please upgrade rtl_wmbus.
(rtlwmbus) using command: ERRFILE=$(mktemp -t wmbusmeters_rtlsdr.XXXXXXXXXXXX) ; echo ERRFILE=$ERRFILE ;  date -Iseconds > $ERRFILE ; tail -f $ERRFILE & /usr/bin/rtl_sdr  -d 0 -f 868.625M -s 1.6e6 - 2>>$ERRFILE | /usr/bin/rtl_wmbus -s
(rtlwmbus) opening
(bgshell) exec background "/bin/sh"
(serial) EVENT thread interrupted
(bgshell) arg "-c"
(bgshell) arg "ERRFILE=$(mktemp -t wmbusmeters_rtlsdr.XXXXXXXXXXXX) ; echo ERRFILE=$ERRFILE ;  date -Iseconds > $ERRFILE ; tail -f $ERRFILE & /usr/bin/rtl_sdr  -d 0 -f 868.625M -s 1.6e6 - 2>>$ERRFILE | /usr/bin/rtl_wmbus -s"
(serialcmd) opened /bin/sh pid 1160 fd 141 (rtlwmbus)
(main) regular reset of rtlwmbus  will happen every 82800 seconds
(wmbus) no alarm (expected activity) for rtlwmbus
(serial) received ascii "ERRFILE=/tmp/wmbusmeters_rtlsdr.XXXXXXhbembK<0A>2024-02-11T20:11:23+00:00<0A>"
Lost  closing rtlwmbus
(wmbus) closing....
(wmbus) deleted rtlwmbus
(serialcmd) closed /bin/sh pid=1143 fd=-1 (rtlwmbus)
(rtlwmbus) checkRTLWMBusFrame "ERRFILE=/tmp/wmbusmeters_rtlsdr.XXXXXXhbembK<0A>2024-02-11T20:11:23+00:00<0A>"
(rtlwmbus) only text
(rtlwmbus) checkRTLWMBusFrame "2024-02-11T20:11:23+00:00<0A>"
(rtlwmbus) only text
(serial) received ascii "Found 1 device(s):<0A>"
(rtlwmbus) checkRTLWMBusFrame "Found 1 device(s):<0A>"
(rtlwmbus) only text
(serial) EVENT thread interrupted
(bgshell) 1160 exited with return code 0
(serial) closing non working fd=141 ""
(wmbus) disconnected  rtlwmbus
(serialcmd) closed /bin/sh pid=1160 fd=141 (rtlwmbus)
```

**Comment by BIBOLV** [comment]
Tested image on arm64 with rtl_sdr and it works. 
Tried alternative config
```
device=rtlwmbus:CMD(ERRFILE=$(mktemp -t wmbusmeters_rtlsdr.XXXXXXXXXXXX) && echo ERRFILE=$ERRFILE && date -Iseconds > $ERRFILE && tail -f $ERRFILE & /usr/bin/rtl_sdr -d 0 -f 868.625M -s 1.6e6 - 2>>$ERRFILE | /usr/bin/rtl_wmbus -s)
```
but it does not work, so this can`t be implemented in ha-addon straight away.

**Comment by weetmuts** [comment]
The weird temporary file is only needed when we do not know which rtl_sdr we are using, to workaround the bug.
If we built the latest rtl_sdr then we can fall back to the normal pipeline, since we do not have to pipe 2>/dev/null
which is the old workaround for the bug, but which hides any rtl_sdr errors, which is potentially a problem.

Does it work with this cmdline?

device=rtlwmbus:CMD(/usr/bin/rtl_sdr -d 0 -f 868.625M -s 1.6e6 - | /usr/bin/rtl_wmbus -s -f)

**Comment by BIBOLV** [comment]
Looks like my dongle is dying - does not respond any more 😢 
Can`t check.

**Comment by testuser7** [comment]
> Looks like my dongle is dying - does not respond any more 😢 Can`t check.

What does `rtl_433` return?

**Comment by BIBOLV** [comment]
Dongle usb connector is loose - will try to find extender somewhere and see if it helps.

**Comment by testuser7** [comment]
You can also try using `rtl_433` like this:
```
rtl_433 -d 0 -R 0 -f 868.625M -s 1.6m -w - | rtl_wmbus -s
```

**Comment by weetmuts** [comment]
@testuser7 It is merged please test!

**Comment by testuser7** [comment]
> @testuser7 It is merged please test!

Ok, I'm testing the `latest` `amd64` version from Docker Hub.

**Pull request merged**
