### PR TITLE
Update driver_hydrus.cc

### PR DESCRIPTION
**Pull request by G-R-O**
Added detection of INTEGRA METERING AG
Integra Aquastream AQS-W8

### CODE REVIEW

**Comment by G-R-O** [comment]
https://wmbusmeters.org/analyze/4644B42557920410050e7237329305B42501075B0030257366049BB8cacc58e7cBae05BB7417eda7d6e5c5eBB0e9f861a5f702f83a98ef77B989Bc344c374af35f87363ed01452:auto:B94D005FB83000A1A3B3A74B7BD8405A

**Comment by tbandixen** [comment]
Here you find the protocoll for the AQS-W8:
https://cdn.filestackcontent.com/D9I9YjyTiyS194qAIrHR?policy=eyJleHBpcnkiOjQwNzA5MDUyMDAsImNhbGwiOlsicmVhZCJdfQ==&signature=95d016cd47d9a9ae17ec16253524118bd5e321495273df983cec710e98e8e2b4

**Comment by weetmuts** [comment]
Thanks! It is a new meter. I have added the new driver aquastream. Check it out here: https://github.com/wmbusmeters/wmbusmeters/blob/master/drivers/src/aquastream.xmq

Please test!

**Comment by weetmuts** [comment]
You can try your wmbusmeters.org link again and it will look fine.

**Comment by tbandixen** [comment]
Thank you! 👍

**Pull request closed without merging**
