### PR TITLE
Add new driver for itron heat meter

### PR DESCRIPTION
**Pull request by Andi252**
The pull request adds a new driver for an itron heat meter. See discussion #1081.

The meter is called [UltraMaXX](https://www.itron.com/emea/solutions/product-catalog/cf-ultramaxx-mk)
and the RF module is called [EquaScan hMIU RF](https://www.itron.com/emea/solutions/product-catalog/equascan-hmiu-rf)

was extended to #1054

### CODE REVIEW

**Comment by Andi252** [comment]
How are the defines for dd-mfct fields created? My meter produces the id 9726 (ITW) and the meter from #1054 creates the id 97a6. I could add this second meter into the driver, but I don't know how to add the second id.

**Comment by Andi252** [comment]
The Itron-Meter from #1054 produces a dd-mfct of 97a6 which decodes into MANFCODE('i','T','W'), when I add this MANFCODE('i','T','W') to my driver the frame from #1054 is decoded and detected correctly.

@weetmuts do you know of other meters where the MANFCODE is not produced from upper case charaters?
Should I add a funktion with "normalizes" the dd-mfct before matching?

**Comment by Andi252** [comment]
I tried to find a definition of the mfct in the offical OMS specification. But the only definition I could find was the "3 times upper case letter" which I would interpret as 3 * 5 bit => 15 bit of total length. In the frame the space available is 16 bit. I couldn'f find a special purpose of this additional bit. Therefore any mfct value should be between 'AAA' = 1057 or 0x0421 and 'ZZZ' = 31710 or 0x7bde.

Unfortunately I could find several test frames in the code which have values > 31710.

@weetmuts What is the best way to handle these invalid frames?

**Comment by Andi252** [comment]
@weetmuts what do you need to accept the pull request?

**Comment by weetmuts** [comment]
Many thanks @Andi252 ! Great work in writing the c++ driver and many thanks for the fix for the weird iTW and aPT manufacturer fields. 

Nowadays, the drivers are text files stored in drivers/src 
I rewrote your code into a new driver: https://github.com/wmbusmeters/wmbusmeters/blob/master/drivers/src/itronheat.xmq

I commited the iTW workaround separately as well.
Many thanks! This pull request can be closed without a merge.

**Comment by Andi252** [comment]
@weetmuts thanks for converting the driver into the xmq format.

**Pull request closed without merging**
